### PR TITLE
Added script called tidy-analyze to make analysis of wordlist files e…

### PR DESCRIPTION
**Pull request by dmuth**
Okay, here's my contribution!  A few notes:

- I noticed that some of the Strongbox wordlists were carraige-return terminated, which tidy didn't seem to like.  I can file a separate issue for that, if you like.
-I didn't run level 4 (`tidy -AAAA`) because it would have taken too long.  Could do an overnight run though if you want.
- Added CSVs from level 1 through level 3 (`-A` through `-AAA`) and a Google Sheet.

On the topic of "which list is better/best", I know that more entropy is better, but the other lists properties were outside of my wheelhouse.  It's a topic that I'm happy to dig into more, but if you want to evaluate the results, feel free to do so!

### CODE REVIEW

**Comment by sts10** [comment]
Wow, awesome! 

> I noticed that some of the Strongbox wordlists were carraige-return terminated, which tidy didn't seem to like. I can file a separate issue for that, if you like.

Yeah, I guess I need to work get Tidy to handle such cases. BUT for this project I think I'm going to ignore the fandom lists in the Strongbox repo -- they have a number of issues with them. I also don't love the non-English lists in the Strongbox repo: they have a lot of punctuation and repeated letters. I have been in contact with Mark at Strongbox -- think they'll be pushing some fun changes soon. But for now, if it's cool with you, I think I'm going to remove all the Strongbox list info from the CSVs you've provided for now. 

> On the topic of "which list is better/best", I know that more entropy is better, but the other lists properties were outside of my wheelhouse. It's a topic that I'm happy to dig into more, but if you want to evaluate the results, feel free to do so!

Yeah, @atoponce and I were discussing this: we both agree that we don't think we're currently able to really rank/grade word lists. I still think this project is useful.

**Comment by sts10** [comment]
>  I didn't run level 4 (`tidy -AAAA`) because it would have taken too long. Could do an overnight run though if you want.

Unfortunately, 4 `A`s runs the uniquely decodable check, using [Sardinas-Patterson](https://en.wikipedia.org/wiki/Sardinas%E2%80%93Patterson_algorithm), which I'd argue is a key piece of information to know about a given list. As an example, my beloved [Orchard Street Wordlists](https://github.com/sts10/orchard-street-wordlists) have prefix and suffix words, but _are_ uniquely decodable. 3 `A`s doesn't convey this information.

Part of my philosophy in making Tidy is to always prefer thoroughness to speed. The idea being that creating a word list isn't something most people are going to do that often. I could get into threads to speed up the processing, but I (still) don't want to complicate the already complex code surrounding unique decodability. 

I'll see if I can get a good run in tonight. Might skip the monster NSA word list though... 

Thanks again for this awesome work!!

**Comment by sts10** [comment]
Is there any way we could add a last column to the CSVs called "Words sample" that takes the first 6-word sample from running `tidy --samples`? Feel like that would help people get a taste for the words on the list, ya know?

**Comment by dmuth** [comment]
> Is there any way we could add a last column to the CSVs called "Words sample" that takes the first 6-word sample from running tidy --samples?

I can do it, but it's gonna take a little overhauling of my shell script.

Before we go down that route, I wanted to ask if there was any chance of adding JSON output to `tidy` itself, like with a `--json` switch or similar?  Then I could parse the different outputs all in the same way with `jq`.

**Comment by sts10** [comment]
> I can do it, but it's gonna take a little overhauling of my shell script.

Now that I've used the script and thought it over a bit, I don't think it's worth bending over backwards for. There are only so many lists to audit, so even if we had to manually add some word samples to the last column that wouldn't be that big  a deal. 

> Before we go down that route, I wanted to ask if there was any chance of adding JSON output to tidy itself, like with a --json switch or similar? Then I could parse the different outputs all in the same way with jq.

That's an interesting idea! I'm a little wary of building out the attributes code of Tidy much more -- it might be time to split it off into a separate tool? I'll have a think on it.

**Comment by dmuth** [comment]
> That's an interesting idea! I'm a little wary of building out the attributes code of Tidy much more -- it might be time to split it off into a separate tool? I'll have a think on it.

My dayjob involves lots and lots of automation, so I'm used to thinking in terms of glue, and JSON does make for great glue.

If you want to let this JSON support idea sit for a few months, I'm (slowly) picking up Rust, and I'd be happy to try my hand at submitting a PR to `tidy` to do that when I'm get to the point where I feel I do so.

**Pull request merged**
